### ISSUE TITLE
How can I listen to the client events like "ready" or "end"?

### ISSUE THREAD

**Issue by fractalawareness** [realtymaps/promise-ftp#10]
I want to handle the "ready" and "end" events so I need to add some listeners. But obviously I can not make just client.on because of "client.on is not a function".
I think this could be related with the https://github.com/realtymaps/promise-ftp/issues/8 - just make the RAW client accessible.

**Comment by zacronos** [comment]
The promise logic should wait for those sort of events before resolving.  If you want to handle things using event listeners, perhaps you should consider using `ftp` instead of `promise-ftp`.

Can you explain the use case to me for why you need to handle things on the event handler level?

**Comment by fractalawareness** [comment]
I want to add logging for every time the connection is lost and every time it reconnects again.

**Comment by zacronos** [comment]
Hmm, this library goes to some effort to make reconnecting completely transparent, so I'm not sure why you'd want to log it.  But, if you do, you do.  I'm going to close this ticket since #8 would solve it.
