### ISSUE TITLE
NPM have some problem with peerDependencies

### ISSUE THREAD

**Issue by GAMELASTER** [realtymaps/promise-ftp#15]
Sorry for bad written title, I don't get better describing title.
```
npm install promise-sftp promise-ftp --save
npm WARN peerDependencies The peer dependency promise-ftp-common@^1.1.5 included from promise-ftp will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency promise-ftp-common@^1.1.2 included from promise-sftp will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by zacronos** [comment]
This has already been handled for `promise-sftp` and `promise-ftp`; `promise-ftp-common` is listed as both a peer dependency and also a regular dependency, as suggested by https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/  There is nothing I can do to make the warning go away, even though it isn't a problem for these modules.

For further discussion of the issue specifically in the context of `promise-sftp` and `promise-ftp`, see https://github.com/realtymaps/promise-ftp/issues/12
