### ISSUE TITLE
All wrapped methods should probably reject on socket error

### ISSUE THREAD

**Issue by motiz88** [realtymaps/promise-ftp#2]
The current wrapping logic runs the risk of creating forever-pending promises in case of socket errors. These socket errors are not otherwise exposed by `promise-ftp`'s API.

I'm getting good mileage out of a change [over at my fork](https://github.com/motiz88/promise-ftp/compare/5da8231be8054553add1ce95bd8d531888be0f60...motiz88:master) which I have published as `@motiz88/promise-ftp` v2.1.1. It attaches a handler using `once('error', ...)` and takes care to detach it if the promise is either resolved or rejected the normal way.

I'll happily submit a PR once I know your position on #1 (which is included in my `master` branch).

**Comment by zacronos** [comment]
I'm a little unclear on the situation which can cause the forever-pending promises.  With that said, go ahead and create the PR, and I'll take a look.

**Comment by frehner** [comment]
I think this is related to an issue I'm running into as well. If not, let me know. But it appears that the FTP server that I connect to occasionally just dies/becomes unreachable for a small amount of time (it's not my server, so I can't tell why). The promise is never completed or rejected, so my code just hangs for forever until I manually go in and make it quit.

**Comment by zacronos** [comment]
@frehner, I never got a PR for this from @motiz88, but @nmccready created one.  Unfortunately, there were some minor merge conflicts that never got resolved.  I'm no longer actively working on the project that uses this module, so I haven't circled back to try to handle the conflicts myself.  But, if you or anyone else wants to do it, I'd gladly review and merge it.

**Comment by frehner** [comment]
Sounds good. Thanks for this repo, it's great. I'll try to take a look at it, though I don't know coffee script very well
