### ISSUE TITLE
Bad FTP config => uncatchable error

### ISSUE THREAD

**Issue by at-teamexports** [realtymaps/promise-ftp#23]
Hello

I am very happy to use promise-ftp and promise-sftp libs.
Unfortunately, I found a little hole in the racket.
In my program, the entry is a configuration object with server, port, login, password etc. And the Boolean telling if it is FTP or SFTP. Thus I can use promise-ftp or promise-sftp.
The problem occurs when the configuration says FTP whereas it is SFTP.
Indeed, line 329 of connection.js file, debug says:
`SSH-2.0-OpenSSH`
And 30 seconds later:
```
$Idle timeout...
$	Disconnecting
```
I think what is happening here is that FTP server is waiting for the client to begin a connection, and the client is waiting the server to begin the hand-check.
After server timeout, thread shuts down and no error is raised. A console.log or a break point, in the promise catch method does not show anything.
It would be great to be able to catch this kind of configuration error because entry FTP configuration is not controllable.

Thanks for your help.
Here is a concrete code to test this issue:
```javascript
const PromiseFtp = require('promise-ftp'), PromiseSftp = require('promise-sftp');
let config = {
    "host":"SFTP server", "user":"user", "port":22, "password":"password",
    "Sftp": false // wrong value => connect() should raise an error
};
let ftpSender = null;
if (config.Sftp) {
    ftpSender = new PromiseSftp();
} else {
    ftpSender = new PromiseFtp();
}
ftpSender.connect(config)
    .then(() => {
        console.log('connection established'); // never goes here
    })
    .catch((error) => {
        console.log('error:' + error); // never goes here
    });
```

**Comment by zacronos** [comment]
This sounds like a specific case of #2, which would be fixed by #6 if it didn't have merge conflicts.  If someone would like to create a version of the #6 PR and fix the merge conflicts, I'd be happy to merge it and handle this issue.

**Comment by zacronos** [comment]
This might be fixed now as a result of https://github.com/realtymaps/promise-ftp/pull/24

**Comment by johngrogg** [comment]
@zacronos Any chance a new release can be built so the fix in #24 is available?

**Comment by zacronos** [comment]
Sure, I'll cut a release tomorrow.

**Comment by zacronos** [comment]
@johngrogg  v1.3.5 released
