### ISSUE TITLE
How to delete a files after downloaded

### ISSUE THREAD

**Issue by kidrock1** [realtymaps/promise-ftp#7]
Hi, i can delete files after download.  Maybe I do not fully understand the promise in js. Here is my code:

```
var ftp = new PromiseFtp();
  ftp.connect({host: '------', user: '----------', password: '------------'})
  .then(function (serverMessage) {
    console.log('Server message: '+serverMessage);
    return ftp.list('/');
  }).then(function (list) {
    list.forEach(function (element, index, array) {
        if (element.name !== '..' && element.name !== '.'){
            console.log(element.name)
        }
    })

  }).then(function () {
    return ftp.end();
  });
```

What should I do next?

**Comment by zacronos** [comment]
Replace your `console.log` statements with the command to delete via FTP -- and more importantly, replace `list.forEach` with `Promise.each`.

https://github.com/petkaantonov/bluebird/blob/2.x/API.md#eachfunction-iterator---promise
