### ISSUE TITLE
How to get RAW ftp client?

### ISSUE THREAD

**Issue by dkMorlok** [realtymaps/promise-ftp#8]
Is there any way to get raw FTP client?
I need access to some client properties (`client._queue.length`).

**Comment by fractalawareness** [comment]
+1

**Comment by zacronos** [comment]
There is currently no way to do this, but if someone would like to make a PR to expose the client, I'll gladly take a look and merge it.

**Comment by fractalawareness** [comment]
https://github.com/realtymaps/promise-ftp/pull/11

**Comment by zacronos** [comment]
PR merged into v1.3.0
